bookstore/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views




urlpatterns = [
    # path('',views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    # # path('login/', views.loginPage, name='login'),
    # # path('register/', views.registerPage, name='register'),
    # # path('logout/', views.logoutUser, name='logout'),
    #
    # path('reset_password/', auth_views.PasswordResetView.as_view(template_name="bookstore/password_reset.html"), name="reset_password"),
    # path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="bookstore/password_reset_sent.html"), name="password_reset_done"),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="bookstore/password_reset_confirm.html"), name="password_reset_confirm"),
    # path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="bookstore/password_reset_complete.html"), name="password_reset_complete"),
    path('search_products', views.search_products, name='search-products'),
    path('search/', views.search, name='search'),
]

bookstore_project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from bookstore import views
from bookstore import views as store_views
from bookstore.views import store, ProductDetailView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bookstore.urls')),
    path('',views.store,name='store'),
    # path('',ProductView.as_view(), name='store'),
    path('update_item/',views.updateitem,name='update_item'),
    path('process_order/',views.processOrder,name='process_order'),
    path('contact_us/', store_views.contact, name='contact_us'),
    path('success/', store_views.thank_you, name='thank_you'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product-detail'),
    # path('product/<int:pk>',views.productdetails,name='product-detail')
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bookstore/models.py
from django.db import models
from django.contrib.auth.models import User
from django.views.generic import DetailView


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    # username = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    # email = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Product(models.Model):
    # sizes = (
    #     ("XS", "extra small"),
    #     ("S", "small"),
    #     ("M", "medium"),
    #     ("L", "large"),
    #     ("XL", 'extra large')
    # )
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    # size = models.CharField(max_length=2,choices=sizes,null=True,blank=False)
    digital = models.BooleanField(default=False, null=True, blank=False)
    description = models.CharField(default='we will add description soon', max_length=5000, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)

    # image

    def __str__(self):
        return self.name

    @property
    def ImageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAdress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    phone_number = models.CharField(max_length=12, default='+37400000000')
    # state = models.CharField(max_length=200,null=False)
    # zipcode = models.CharField(max_length=200,null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

bookstore/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Customer

class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    name = forms.CharField(max_length=200)

    class Meta:
        model = User
        # model = Customer
        fields = ['name', 'username', 'email', 'password1', 'password2']



class NameForm(forms.Form):
    your_name = forms.CharField(label='your-name', max_length=100)

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)


class ContactusForm(forms.Form):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, max_length=500, required=True)

bookstore/views.py
import datetime
import json
from django.http import JsonResponse
from django.shortcuts import render
from .models import *
from django.views.decorators.csrf import csrf_exempt
from .utils import cookieCart, cartData, guestOrder
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from .models import Product
from .forms import CreateUserForm, ContactusForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


# def registerPage(request):
#     if request.user.is_authenticated:
#         return redirect('store')
#     else:
#         form = CreateUserForm()
#
#         if request.method == 'POST':
#             form = CreateUserForm(request.POST)
#             if form.is_valid():
#                 user = form.cleaned_data.get('username')
#                 form.save()
#                 messages.success(request, 'Account was created for ' + user)
#
#                 return redirect('login')
#
#         context = {'form': form}
#         return render(request, 'bookstore/register.html', context)
#
#
# def loginPage(request):
#     if request.user.is_authenticated:
#         return redirect('store')
#     else:
#         if request.method == 'POST':
#             username = request.POST.get('username')
#             password = request.POST.get('password')
#
#             user = authenticate(request, username=username, password=password)
#
#             if user is not None:
#                 login(request, user)
#                 return redirect('store')
#             else:
#                 messages.info(request, 'Username or password is incorrect')
#
#         context = {}
#         return render(request, 'bookstore/login.html', context)

#
# def logoutUser(request):
#     logout(request)
#     return redirect('login')



def store(request):
    data = cartData(request)
    cartItems = data['cartItems']
    products = Product.objects.all()
    product_list = Product.objects.all().order_by('id')
    paginator = Paginator(product_list, 9)
    page_number = request.GET.get('page')
    paginator.get_page(page_number)
    page_obj = paginator.get_page(page_number)
    context = {'products': products, 'cartItems': cartItems, 'shipping': False, 'page_obj': page_obj}
    return render(request, 'bookstore/store.html', context)


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'products'
    template_name = 'bookstore/product_detail.html'


# def productdetails(request,**kwargs):
#     data = cartData(request)
#     cartItems = data['cartItems']
#     order = data['order']
#     items = data['items']
#     products = Product.objects.all()
#     context = {'products':products, 'items': items, 'order': order, 'cartItems': cartItems,}
#     return render(request,'store/product_detail.html',context)
# @login_required(login_url='login')
def cart(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'bookstore/cart.html', context)


# @login_required(login_url='login')
def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'bookstore/checkout.html', context)


# @login_required(login_url='login')
def updateitem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('Product:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)


# @csrf_exempt
# @login_required(login_url='login')
def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAdress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            phone_number=data['shipping']['phone_number']
            # state=data['shipping']['state'],
            # zipcode=data['shipping']['zipcode']
        )

    return JsonResponse('Payment submitted..', safe=False)


# @login_required(login_url='login')
def contact(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    if request.method == 'POST':
        form = ContactusForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            message = form.cleaned_data.get('message')

            subject = 'Someone contacted us'
            content = f"""
            {first_name} {last_name} is trying to contact u .
            Their email address is: {email}
            Message: {message}
            """

            send_mail(subject=subject, message=content,
                      from_email='shopforproject@gmail.com',
                      recipient_list=['shopforproject@gmail.com'])
            return redirect('thank_you')

    else:
        form = ContactusForm()
    context = {'items': items, 'order': order, 'cartItems': cartItems, 'form': form}
    return render(request, 'bookstore/contact_us.html', context)


def thank_you(request):
    return render(request, 'bookstore/thank_you.html')
#
# @login_required(login_url='login')
def search_products(request):
    data = cartData(request)
    cartItems = data['cartItems']

    if request.method == "POST":
        searched = request.POST['searched']
        products = Product.objects.filter(name__contains=searched)

        return render(request,
                      'bookstore/search_products.html',
                      {'searched': searched,
                       'products': products,
                       'cartItems': cartItems}
                      )
    else:
        return render(request,
                      'bookstore/search_products.html',
                      {})


def search(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'bookstore/search.html', context)

bookstore/templates/bookstore/cart.html
{% extends 'bookstore/main.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cart</title>
</head>
<body>
    {% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'store' %}">&#x2190; Continue Shopping</a>

                <br>
                <br>
                  <table class="table">
                      <tr>
                          <th><h5>Items: <strong>{{ order.get_cart_items }}</strong></h5> </th>
                          <th><h5>Total: <strong>${{ order.get_cart_total  }}</strong></h5> </th>
                          <th>
                              <a style="float: right;margin: 5px" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
                          </th>

                      </tr>
                  </table>
            </div>

            <br>

            <div class="box-element">
                <div class="cart-row">
                    <div style="flex: 2"></div>
                    <div style="flex: 2"><strong>Item</strong></div>
                    <div style="flex: 1"><strong>Price</strong></div>
                    <div style="flex: 1"><strong>Quantity</strong></div>
                    <div style="flex: 1"><strong>Total</strong></div>
                </div>
                {% for item in items %}
                    <div class="cart-row">
                        <div style="flex: 2"><img class="row-image" src="{{ item.product.ImageURL }}"></div>
                        <div style="flex: 2"><p>{{ item.product.name }}</p></div>
                        <div style="flex: 1"><p>${{ item.product.price|floatformat:2 }}</p></div>
                        <div style="flex: 1">
                            <p class="quantity">x{{ item.quantity }}</p>
                            <div class="quantity">
                                <a href="{% url 'cart' %}"><img data-product="{{ item.product.id }}" data-action="add" class="chg-quantity update-cart" src="{% static 'images/arrow-up.png' %}"></a>

                                <a href="{% url 'cart' %}"><img data-product="{{ item.product.id }}" data-action="remove" class="chg-quantity update-cart" src="{% static 'images/arrow-down.png' %}"></a>
                            </div>
                        </div>
                        <div style="flex: 1">${{ item.get_total }}</div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>
    {% endblock content %}
</body>
</html>

bookstore/templates/bookstore/checkout.html
{% extends 'bookstore/main.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Checkout</title>
</head>
<body>
    {% block content %}
        <div class="row">
            <div class="col-lg-6">
                <div class="box-element" id="form-wrapper">
                    <form id="form">
                        {% csrf_token %}
                        <div id="user-info">
                            <div class="form-field">
                                <input required class="form-control" type="text" name="name" placeholder="Name..">
                            </div>
                            <div class="form-field">
                                <input required class="form-control" type="email" name="email" placeholder="Email..">
                            </div>
                        </div>

                        <div id="shipping-info">
                            <hr>
                            <p>Shipping Information:</p>
                            <hr>
                            <div class="form-field">
                                <input class="form-control" type="text" name="address" placeholder="Address..">
                            </div>
                            <div class="form-field">
                                <input class="form-control" type="text" name="city" placeholder="City..">
                            </div>
                            <div class="form-field">
                                  <input class="form-control" type="text" name="phone_number" placeholder="+374..">
{#                                <input class="form-control" type="text" name="state" placeholder="State..">#}
                            </div>
                            <div class="form-field">
{#                                <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">#}
                            </div>
                            <div class="form-field">
{#                                <input class="form-control" type="text" name="country" placeholder="Zip code..">#}
                            </div>
                        </div>
                        <hr>
                        <input id="form-button" class="btn btn-success btn-block" type="submit" value="continue">
                    </form>
                </div>
                <br>

                <div class="box-element hidden" id="payment-info">
                    <small>PayPal options</small>
                     <div id="paypal-button-container"></div>
{#                    <button id="make-payment">Pay</button>#}
                </div>

            </div>

            <div class="col-lg-6">
                <div class="box-element">
                    <a class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190;Back to Cart</a>
                    <hr>
                    <h3>Order Summary</h3>

                    <hr>
                    {% for item in items %}
                    <div class="cart-row">
                         <div style="flex: 2"><img class="row-image" src="{{ item.product.ImageURL }}"></div>
                    <div style="flex: 2">{{ item.product.name}}</div>
                    <div style="flex: 1">${{ item.product.price|floatformat:2 }}</div>
                        <div style="flex: 1">x{{ item.quantity }}</div>
                    </div>
                    {% endfor %}
                    <h5>Items:   x{{ order.get_cart_items }}</h5>
                    <h4>Total:   ${{ order.get_cart_total }}</h4>
                </div>
            </div>
        </div>
         <script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>
         <script>
            var total = '{{ order.get_cart_total }}'
            // Render the PayPal button into #paypal-button-container
            paypal.Buttons({

                // Set up the transaction
                createOrder: function(data, actions) {
                    return actions.order.create({
                        purchase_units: [{
                            amount: {
                                value: parseFloat(total).toFixed(2)
                            }
                        }]
                    });
                },

                // Finalize the transaction
                onApprove: function(data, actions) {
                    return actions.order.capture().then(function(orderData) {
                        submitFormData()

                    });
                }


            }).render('#paypal-button-container');
        </script>

        <script type="text/javascript">
        var shipping = '{{ order.shipping }}'


        if (shipping == 'False'){
            document.getElementById('shipping-info').innerHTML = ''
        }

        if (user != 'AnonymousUser'){
            document.getElementById('user-info').innerHTML = ''
        }

        if (shipping == 'False' && user != 'AnonymousUser'){
            document.getElementById('form-wrapper').classList.add("hidden");
            document.getElementById('payment-info').classList.remove("hidden");
        }

        var form = document.getElementById('form')

        csrftoken = form.getElementsByTagName("input")[0].value
        console.log('Newtoken', form.getElementsByTagName("input")[0].value)

        form.addEventListener('submit',function(e){
            e.preventDefault()
            console.log('form submitted...')
            document.getElementById('form-button').classList.add("hidden");
            document.getElementById('payment-info').classList.remove("hidden")
        })

        document.getElementById('make-payment').addEventListener("click", function(e){
            submitFormData()
        })

        function submitFormData(){
            console.log('Payment button clicked')

            var userFormData = {
                'name': null,
                'email':null,
                'total':total
            }
            var shippingInfo = {
                'address': null,
                'city':null,
                'phone_number':null,
                {#'state':null,#}
                {#'zipcode':null,#}
            }

            if (shipping != 'False'){
                shippingInfo.address = form.address.value
                shippingInfo.city = form.city.value
                shippingInfo.phone_number = form.phone_number.value
                {#shippingInfo.state = form.state.value#}
                {#shippingInfo.zipcode = form.zipcode.value#}
            }

            if (user == 'AnonymousUser'){
                userFormData.name = form.name.value
                userFormData.email = form.email.value
            }

            var url = "/process_order/"
            fetch(url,{
                method:'POST',
                headers:{
                    'Content-Type':'application/json',
                    'X-CSRFToken':csrftoken,
                },
                body:JSON.stringify({'form':userFormData,'shipping':shippingInfo})
            })

            .then((response) => response.json())
            .then((data) => {
                console.log('Success:', data);
                alert('Transaction completed');

                cart = {}
                document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"

                window.location.href = "{% url 'store' %}"
                })


        }

        </script>


    {% endblock content %}

</body>
</html>

bookstore/templates/bookstore/contact_us.html
{% extends 'bookstore/main.html' %}
  {% block title %}Contact Us{% endblock title %}

  {% block content %}
  <h1>Contact us</h1>

  {% if submitted %}
    <p class="success">
     Your message was submitted successfully. Thank you.
   </p>

 {% else %}
   <form action="" method="post" novalidate>
   <table>
     {{ form.as_table }}
     <tr>
       <td>&nbsp;</td>
       <td><input type="submit" value="Submit"></td>
     </tr>
   </table>
   {% csrf_token %}
   </form>
{% endif %}
{% endblock content %}

bookstore/templates/bookstore/password_reset.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark" style="background-color: #059033">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'register' %}">Create A New Account</a><br><br>
                                <a href="{% url 'login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}

{#{% block content %}#}
{#	<style>#}
{#		body,#}
{#		html {#}
{#			margin: 0;#}
{#			padding: 0;#}
{#			height: 100%;#}
{#			background: white !important;#}
{#		}#}
{#		.user_card {#}
{#			width: 350px;#}
{#			margin-top: auto;#}
{#			margin-bottom: auto;#}
{#			background: white;#}
{#			position: relative;#}
{#			display: flex;#}
{#			justify-content: center;#}
{#			flex-direction: column;#}
{#			padding: 10px;#}
{#			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
{#			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
{#			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
{#			border-radius: 5px;#}
{##}
{#		}#}
{##}
{#		.form_container {#}
{#			margin-top: 20px;#}
{#		}#}
{##}
{#		#form-title{#}
{#			color: 	#202020;#}
{##}
{#		}#}
{##}
{#		.login_btn {#}
{#			width: 100%;#}
{#			background: #059033 !important;#}
{#			color: white !important;#}
{#		}#}
{#		.login_btn:focus {#}
{#			box-shadow: none !important;#}
{#			outline: 0px !important;#}
{#		}#}
{#		.login_container {#}
{#			padding: 0 2rem;#}
{#		}#}
{#		.input-group-text {#}
{#			background: #C0C0C0 !important;#}
{#			color: white !important;#}
{#			border: 0 !important;#}
{#			border-radius: 0.25rem 0 0 0.25rem !important;#}
{#		}#}
{#		.input_user,#}
{#		.input_pass:focus {#}
{#			box-shadow: none !important;#}
{#			outline: 0px !important;#}
{#		}#}
{##}
{#		#messages{#}
{#			background-color: grey;#}
{#			color: #fff;#}
{#			padding: 10px;#}
{#			margin-top: 10px;#}
{#		}#}
{#	</style>#}
{##}
{#</head>#}
{#<body>#}
{#	<div class="container h-100">#}
{#		<div class="d-flex justify-content-center h-100">#}
{#			<div class="user_card">#}
{#				<div class="d-flex justify-content-center">#}
{#					<h4 id="form-title">Forgot your password?</h4>#}
{#				</div>#}
{#                <p style="text-align: center">Enter your email address below, and we'll email instructions for setting a new one.</p>#}
{#				<div class="d-flex justify-content-center form_container">#}
{#					<form method="POST" action="">#}
{#                            {% csrf_token %}#}
{#                            <div class="input-group mb-2">#}
{#                                <div class="input-group-append">#}
{#                                    <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>#}
{#                                </div>#}
{#                                {{ form.email }}#}
{#                            </div>#}
{##}
{##}
{#	                        <div class="d-flex justify-content-center mt-3 login_container">#}
{#				 				<input class="btn login_btn" type="submit" value="Send me instructions!">#}
{#				   			</div>#}
{#					</form>#}
{##}
{#				</div>#}
{##}
{#				</div>#}
{#			</div>#}
{#		</div>#}
{#	</div>#}
{#{% endblock content %}#}
{#</body>#}
{##}
{#</html>#}

bookstore/templates/bookstore/search.html
{% extends 'bookstore/main.html' %}